console.log('----- ARRAY METHODS -----');
/** 
    push(), pop(), unshift(), shift(), indexOf(), Arrat.isArray()
    forEach()
    includes()
    filter()
    map()
    reduce()
    some()
    every()
    sort()
    Array.from()
    Array.of()
    reverse()
    join()
    slice()
    splice()
    find()
    findIndex()
    split()
    entries()
    keys()
*/ 