/**
 * 2nd App
 * The DiceRoller app displays a random Dice face image generated by an algorithm on tap on a button.
 * There is also a 2nd image of Dice that also randomly displays random number on Dice face.
 */

import React, { useState } from 'react';
import {
  View,
  StyleSheet,
  Text,
  StatusBar,
  Image,
  Pressable,
} from 'react-native';

import DiceOne from './assets/dice1.png';
import DiceTwo from './assets/dice2.png';
import DiceThree from './assets/dice3.png';
import DiceFour from './assets/dice4.png';
import DiceFive from './assets/dice5.png';
import DiceSix from './assets/dice6.png';

function DiceRoller(props) {
  const [diceOneUri, setDiceOneUri] = useState(DiceOne);
  const [diceTwoUri, setDiceTwoUri] = useState(DiceTwo);

  const rollDice = () => {
    let randomNumberOne = Math.floor(Math.random() * 6) + 1;
    let randomNumberTwo = Math.floor(Math.random() * 6) + 1;

    switch (randomNumberOne) {
      case 1:
        setDiceOneUri(DiceOne);
        break;
      case 2:
        setDiceOneUri(DiceTwo);
        break;
      case 3:
        setDiceOneUri(DiceThree);
        break;
      case 4:
        setDiceOneUri(DiceFour);
        break;
      case 5:
        setDiceOneUri(DiceFive);
        break;
      case 6:
        setDiceOneUri(DiceSix);
        break;

      default:
        setDiceOneUri(randomNumberOne);
        break;
    }

    switch (randomNumberTwo) {
      case 1:
        setDiceTwoUri(DiceOne);
        break;
      case 2:
        setDiceTwoUri(DiceTwo);
        break;
      case 3:
        setDiceTwoUri(DiceThree);
        break;
      case 4:
        setDiceTwoUri(DiceFour);
        break;
      case 5:
        setDiceTwoUri(DiceFive);
        break;
      case 6:
        setDiceTwoUri(DiceSix);
        break;

      default:
        setDiceTwoUri(randomNumber);
        break;
    }
  };

  return (
    <>
      <StatusBar backgroundColor="#222831" />
      <View style={styles.container}>
        <Pressable onPress={rollDice}>
          <View style={styles.diceContainer}>
            <Image source={diceOneUri} style={styles.image} />
            <Image source={diceTwoUri} style={styles.image} />
          </View>
          {/* <Text style={styles.rollBtn}>Roll the dice!</Text> */}
        </Pressable>
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: StatusBar.currentHeight,
    backgroundColor: '#222831',
  },
  image: {
    width: 180,
    height: 180,
  },
  rollBtn: {
    fontSize: 18,
    marginTop: 30,
    color: '#F2A365',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderColor: '#30475E',
    borderRadius: 5,
    borderWidth: 3,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  diceContainer: {
    flexDirection: 'row',
    paddingLeft: 20,
    paddingRight: 20,
  },
});

export default DiceRoller;
